version: "3"

services:
  flarum:
    image: mondedie/docker-flarum:0.1.0-beta.11.1-stable
    container_name: flarum
    env_file:
      - ./flarum/flarum.env
    volumes:
      - ./flarum/assets:/flarum/app/public/assets
      - ./flarum/extensions:/flarum/app/extensions
      - ./flarum/nginx:/etc/nginx/conf.d
    depends_on:
      - mariadb
    ports: 
      - "3000:8888"

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=flarum@123
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=flarum@123
    volumes:
      - ./mariadb/db:/var/lib/mysql
